name: "Expire Snapshots"

on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  expire-branches:
    name: "Expire Branches"
    runs-on: ubuntu-latest

    steps:
    - name: "Run Expiration Action"
      uses: readaheadeu/rae-actions/expire-branches@main
      with:
        date: "1 week ago"
        repository: ${{ github.repository }}
        wildcard: "repo-snapshot-*"
